# Generated by Django 3.0.3 on 2020-09-12 15:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsaStates',
            fields=[
                ('state_fips', models.AutoField(db_column='STATE_FIPS', primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('state_name', models.CharField(blank=True, max_length=25, null=True)),
                ('state_fips_0', models.CharField(blank=True, db_column='state_fips', max_length=2, null=True)),
                ('state_abbr', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'USA_States',
                'managed': False,
            },
        ),
    ]
